services:
  db:
    restart: always
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: ./classconnect-api
    ports:
      - "8080:8080"
    depends_on:
      - db
  notification_service:
    restart: always
    build: ./classconnect-notification-service
    depends_on:
      - db
  bot:
    restart: always
    build: ./classconnect-bot
